### PR TITLE
Update README.md with functioning link for node template

### PR DESCRIPTION
**Pull request by Yung-Beef**
I'm probably a little in over my head here but a lot of the "Substrate" stuff doesn't work/exist anymore. Updating to what works today.

### CODE REVIEW

**Comment by shawntabrizi** [comment]
tyvm

**Review by shawntabrizi — APPROVED** [review]

**Comment by shawntabrizi** [comment]
@Yung-Beef i made some more updates to this workshop (updated links, videos, etc...).

The `proof-of-existence` workshop in this repo probably still a little fucked up. I need to convert it into the [gitorial](https://github.com/gitorial-sdk) format, and maintain it there.

**Comment by Yung-Beef** [comment]
> The `proof-of-existence` workshop in this repo probably still a little fucked up. I need to convert it into the [gitorial](https://github.com/gitorial-sdk) format, and maintain it there.

Yeah it definitely is @shawntabrizi. I can clone the solochain template and build it, but if I replace the pallet-template/src/lib with what's in the tutorial it won't build (missing weights in the config trait and some other super cryptic error). Yesterday on my first attempt I was getting some error due to std leaking into the sp_io crate or something, but I re-did the steps today and didn't get that (got the weight error instead) so I don't know what's going on.

Thanks for creating the rest of this though, very helpful!

**Comment by shawntabrizi** [comment]
@Yung-Beef try https://github.com/shawntabrizi/substrate-collectables-workshop

This is where i spent my energy recently to create a really high quality "first tutorial" for Polkadot SDK.

Would love any feedback or problems you find :)

**Pull request merged**
